name: 'deploy-v2-indexer'
runs:
  using: 'composite'
  steps:
    - name: -> V2 -- Deploy INDEXER cli in MAINNET
      uses: tensor-hq/eksctl-helm-action@main
      env:
        RELEASE_NAME: ${{ env.INDEXER_RELEASE_NAME_V2 }} # notice
        HOLOGRAPH_VERSION: 'V2'
        #
        ENABLE_DEBUG: 'true'
        HEALTHCHECK: 'true'
        MODE: 'auto'
        ENABLE_UNSAFE: 'true'
        ENABLE_SYNC: 'true'
        ENABLE_PROCESS_BLOCK_RANGE: 'true' # undefined/true
        UPDATE_BLOCK_HEIGHT: 'api' # api/file/disable
        #
        ENABLE_PROCESS_BLOCK_RANGE_arbitrum: 'true' # undefined/true
        ENABLE_PROCESS_BLOCK_RANGE_optimism: 'true'
        ENABLE_PROCESS_BLOCK_RANGE_binance: 'true'
        ENABLE_PROCESS_BLOCK_RANGE_mantle: 'true'
        ENABLE_PROCESS_BLOCK_RANGE_zora: 'true'
        ENABLE_PROCESS_BLOCK_RANGE_avalanche: 'true'
        ENABLE_PROCESS_BLOCK_RANGE_ethereum: 'true'
        ENABLE_PROCESS_BLOCK_RANGE_polygon: 'true'
        ENABLE_PROCESS_BLOCK_RANGE_base: 'true'
        ENABLE_PROCESS_BLOCK_RANGE_linea: 'true'
        #
        AVALANCHE_NETWORK: 'avalanche'
        POLYGON_NETWORK: '{polygon}'
        BINANCE_NETWORK: 'binanceSmartChain'
        MANTLE_NETWORK: '{mantle}'
        ETHEREUM_NETWORK: '{ethereum}'
        OPTIMISM_NETWORK: '{optimism}'
        ARBITRUM_NETWORK: '{arbitrumOne}'
        ZORA_NETWORK: '{zora}'
        BASE_NETWORK: '{base}'
        LINEA_NETWORK: '{linea}'
      with:
        eks_cluster: ${{ env.CLUSTER_NAME }}
        command: |-
          helm upgrade --install $RELEASE_NAME \
          holo-indexer-${{ env.MAINNET_HOLO_INDEXER_HELM_CHART_VERSION }}.tgz \
          -n ${{ env.MAINNET_COMMON_NAMESPACE_V2 }} \
          \
          --set dummy_deployment_namespace=mainnet-cli-dummies \
          \
          --set image.repository=${{ env.ECR_REPOSITORY }} \
          --set image.image_tag=${{ env.IMAGE_TAG }} \
          --set config_file_data=${{ env.INDEXER_HOLO_CONFIG_FILE_DATA }} \
          --set holo_indexer_password=${{ env.MAINNET_HOLO_INDEXER_PASSWORD }} \
          --set HOLO_INDEXER_HOST=$MAINNET_INDEXER_V2_HOLO_INDEXER_HOST \
          --set OPERATOR_API_KEY=$MAINNET_INDEXER_V2_OPERATOR_API_KEY \
          --set HOLOGRAPH_ENVIRONMENT=${{ env.HOLOGRAPH_ENVIRONMENT }} \
          --set HOLOGRAPH_ADDRESS=${{ env.HOLOGRAPH_ADDRESS }} \
          --set HOLOGRAPH_VERSION=${{ env.HOLOGRAPH_VERSION }} \
          --set BLOCK_PROCESSING_VERSION=${{ env.BLOCK_PROCESSING_VERSION }} \
          \
          --set ENABLE_DEBUG=$ENABLE_DEBUG \
          --set ENABLE_SYNC=$ENABLE_SYNC \
          --set HEALTHCHECK=$HEALTHCHECK \
          --set MODE=$MODE \
          \
          --set AVALANCHE_NETWORK="${AVALANCHE_NETWORK}" \
          --set POLYGON_NETWORK="${POLYGON_NETWORK}" \
          --set BINANCE_NETWORK="${BINANCE_NETWORK}" \
          --set MANTLE_NETWORK="${MANTLE_NETWORK}" \
          --set ETHEREUM_NETWORK="${ETHEREUM_NETWORK}" \
          --set OPTIMISM_NETWORK="${OPTIMISM_NETWORK}" \
          --set ARBITRUM_NETWORK="${ARBITRUM_NETWORK}" \
          --set ZORA_NETWORK="${ZORA_NETWORK}" \
          --set BASE_NETWORK="${BASE_NETWORK}" \
          --set LINEA_NETWORK="${LINEA_NETWORK}" \
          \
          --set ENABLE_UNSAFE="${ENABLE_UNSAFE}" \
          --set UPDATE_BLOCK_HEIGHT=$UPDATE_BLOCK_HEIGHT \
          \
          --set ENABLE_PROCESS_BLOCK_RANGE.arbitrum=$ENABLE_PROCESS_BLOCK_RANGE_arbitrum \
          --set ENABLE_PROCESS_BLOCK_RANGE.binance=$ENABLE_PROCESS_BLOCK_RANGE_binance \
          --set ENABLE_PROCESS_BLOCK_RANGE.avalanche=$ENABLE_PROCESS_BLOCK_RANGE_avalanche \
          --set ENABLE_PROCESS_BLOCK_RANGE.optimism=$ENABLE_PROCESS_BLOCK_RANGE_optimism \
          --set ENABLE_PROCESS_BLOCK_RANGE.ethereum=$ENABLE_PROCESS_BLOCK_RANGE_ethereum \
          --set ENABLE_PROCESS_BLOCK_RANGE.polygon=$ENABLE_PROCESS_BLOCK_RANGE_polygon \
          --set ENABLE_PROCESS_BLOCK_RANGE.mantle=$ENABLE_PROCESS_BLOCK_RANGE_mantle \
          --set ENABLE_PROCESS_BLOCK_RANGE.zora=$ENABLE_PROCESS_BLOCK_RANGE_zora \
          --set ENABLE_PROCESS_BLOCK_RANGE.base=$ENABLE_PROCESS_BLOCK_RANGE_base \
          --set ENABLE_PROCESS_BLOCK_RANGE.linea=$ENABLE_PROCESS_BLOCK_RANGE_linea \
          \
          --set mainnet_rpc_config_values.avalanche_rpc_url=$MAINNET_INDEXER_V2_AVALANCHE_RPC_URL \
          --set mainnet_rpc_config_values.polygon_rpc_url=$MAINNET_INDEXER_V2_POLYGON_RPC_URL \
          --set mainnet_rpc_config_values.ethereum_rpc_url=$MAINNET_INDEXER_V2_ETHEREUM_RPC_URL \
          --set mainnet_rpc_config_values.optimism_rpc_url=$MAINNET_INDEXER_V2_OPTIMISM_RPC_URL \
          --set mainnet_rpc_config_values.arbitrum_rpc_url=$MAINNET_INDEXER_V2_ARBITRUM_ONE_RPC_URL \
          --set mainnet_rpc_config_values.binance_rpc_url=$MAINNET_INDEXER_V2_BINANCE_SMART_CHAIN_RPC_URL \
          --set mainnet_rpc_config_values.mantle_rpc_url=$MAINNET_INDEXER_V2_MANTLE_RPC_URL \
          --set mainnet_rpc_config_values.zora_rpc_url=$MAINNET_INDEXER_V2_ZORA_RPC_URL \
          --set mainnet_rpc_config_values.base_rpc_url=$MAINNET_INDEXER_V2_BASE_RPC_URL \
          --set mainnet_rpc_config_values.linea_rpc_url=$MAINNET_INDEXER_V2_LINEA_RPC_URL \
          \
          --set mainnet_rpc_config_values.private_key=$MAINNET_INDEXER_V2_PRIVATE_KEY \
          --set mainnet_rpc_config_values.address=$MAINNET_INDEXER_V2_MAINNET_V2_WALLET_ADDRESS \
          --set mainnet_rpc_config_values.version="beta3" \
          \
          --set datadog_tags.env=${{ env.CLUSTER_NAME }} \
          --set datadog_tags.service=$RELEASE_NAME \
          --set datadog_tags.version=$RELEASE_NAME-${{ env.MAINNET_HOLO_INDEXER_HELM_CHART_VERSION }} \
          \
          --set autoscaling.enabled=false \
          --set replicaCountAvalanche=0 \
          --set replicaCountPolygon=0 \
          --set replicaCountBinance=0 \
          --set replicaCountMantle=0 \
          --set replicaCountEthereum=0 \
          --set replicaCountArbitrum=0 \
          --set replicaCountOptimism=0 \
          --set replicaCountBase=0 \
          --set replicaCountLinea=0 \
          --set replicaCountZora=0 \
          \
          --set sqs.SQS_USER_AWS_ACCESS_KEY_ID=$COMMON_AWS_ACCESS_KEY_ID_SQS \
          --set sqs.SQS_USER_AWS_SECRET_ACCESS_KEY=$COMMON_AWS_SECRET_ACCESS_KEY_SQS \
          --set sqs.SQS_ENDPOINT=$MAINNET_INDEXER_V2_SQS_ENDPOINT \
          --set sqs.SQS_QUEUE_URL=$MAINNET_INDEXER_V2_SQS_QUEUE_URL \
          --set sqs.AWS_REGION=$COMMON_AWS_REGION \
          \
          --values ./holo-indexer/values-v2-mainnet-iv.yaml
