name: 'deploy-indexer'
runs:
  using: "composite"
  steps:
    - name: -> V2 -- Deploy INDEXER cli in staging [namespace -> ${{ env.STG_COMMON_NAMESPACE_V2 }}]
      uses: tensor-hq/eksctl-helm-action@main
      env:
        RELEASE_NAME: ${{ env.INDEXER_RELEASE_NAME_V2 }} # notice
        HOLOGRAPH_VERSION: "V2"
        #
        ENABLE_DEBUG: 'true'
        HEALTHCHECK: 'true'
        MODE: 'auto'
        ENABLE_UNSAFE: 'false'
        ENABLE_SYNC: 'true'
        ENABLE_PROCESS_BLOCK_RANGE: 'true' # undefined/true
        UPDATE_BLOCK_HEIGHT: 'api' # api/file/disable
        #
        ENABLE_PROCESS_BLOCK_RANGE_arbitrum: 'true' # undefined/true
        ENABLE_PROCESS_BLOCK_RANGE_optimism: 'true'
        ENABLE_PROCESS_BLOCK_RANGE_binance: 'true'
        ENABLE_PROCESS_BLOCK_RANGE_mantle: 'true'
        ENABLE_PROCESS_BLOCK_RANGE_zora: 'true'
        ENABLE_PROCESS_BLOCK_RANGE_avalanche: 'true'
        ENABLE_PROCESS_BLOCK_RANGE_ethereum: 'true'
        ENABLE_PROCESS_BLOCK_RANGE_polygon: 'true'
        ENABLE_PROCESS_BLOCK_RANGE_base: 'true'
        ENABLE_PROCESS_BLOCK_RANGE_linea: 'true'
        #
        AVALANCHE_NETWORK: 'avalancheTestnet'
        POLYGON_NETWORK: '{polygonTestnet}'
        BINANCE_NETWORK: 'binanceSmartChainTestnet'
        MANTLE_NETWORK: '{mantleTestnet}'
        ETHEREUM_NETWORK: '{ethereumTestnetSepolia}'
        OPTIMISM_NETWORK: '{optimismTestnetSepolia}'
        ARBITRUM_NETWORK: '{arbitrumTestnetSepolia}'
        ZORA_NETWORK: '{zoraTestnetSepolia}'
        BASE_NETWORK: '{baseTestnetSepolia}'
        LINEA_NETWORK: '{lineaTestnetGoerli}'
      with:
        eks_cluster: ${{ env.CLUSTER_NAME }}
        command: |-
          helm upgrade --install $RELEASE_NAME \
          holo-indexer-${{ env.STG_HOLOGRAPH_INDEXER_HELM_CHART_VERSION }}.tgz \
          -n ${{ env.STG_COMMON_NAMESPACE_V2 }} \
          \
          --set dummy_deployment_namespace=dev-cli-dummies \
          \
          --set image.repository=${{ env.ECR_REPOSITORY }} \
          --set image.image_tag=${{ env.IMAGE_TAG }} \
          --set config_file_data=${{ env.INDEXER_HOLOGRAPH_CONFIG_FILE_DATA }} \
          --set holo_indexer_password=$DEV_INDEXER_V2_PASSWORD \
          --set HOLO_INDEXER_HOST=$DEV_INDEXER_V2_HOLO_INDEXER_HOST \
          --set OPERATOR_API_KEY=$DEV_INDEXER_V2_OPERATOR_API_KEY \
          --set HOLOGRAPH_ENVIRONMENT=${{ env.HOLOGRAPH_ENVIRONMENT }} \
          --set HOLOGRAPH_ADDRESS=$DEV_INDEXER_V2_HOLOGRAPH_ADDRESS \
          --set HOLOGRAPH_VERSION=${{ env.HOLOGRAPH_VERSION }} \
          --set BLOCK_PROCESSING_VERSION=${{ env.BLOCK_PROCESSING_VERSION }} \
          \
          --set ENABLE_DEBUG=$ENABLE_DEBUG \
          --set ENABLE_SYNC=$ENABLE_SYNC \
          --set HEALTHCHECK=$HEALTHCHECK \
          --set MODE=$MODE \
          \
          --set AVALANCHE_NETWORK="${AVALANCHE_NETWORK}" \
          --set POLYGON_NETWORK="${POLYGON_NETWORK}" \
          --set BINANCE_NETWORK="${BINANCE_NETWORK}" \
          --set MANTLE_NETWORK="${MANTLE_NETWORK}" \
          --set ETHEREUM_NETWORK="${ETHEREUM_NETWORK}" \
          --set OPTIMISM_NETWORK="${OPTIMISM_NETWORK}" \
          --set ARBITRUM_NETWORK="${ARBITRUM_NETWORK}" \
          --set ZORA_NETWORK="${ZORA_NETWORK}" \
          --set BASE_NETWORK="${BASE_NETWORK}" \
          --set LINEA_NETWORK="${LINEA_NETWORK}" \
          \
          --set ENABLE_UNSAFE="${ENABLE_UNSAFE}" \
          --set UPDATE_BLOCK_HEIGHT=$UPDATE_BLOCK_HEIGHT \
          \
          --set ENABLE_PROCESS_BLOCK_RANGE.arbitrum=$ENABLE_PROCESS_BLOCK_RANGE_arbitrum \
          --set ENABLE_PROCESS_BLOCK_RANGE.binance=$ENABLE_PROCESS_BLOCK_RANGE_binance \
          --set ENABLE_PROCESS_BLOCK_RANGE.avalanche=$ENABLE_PROCESS_BLOCK_RANGE_avalanche \
          --set ENABLE_PROCESS_BLOCK_RANGE.optimism=$ENABLE_PROCESS_BLOCK_RANGE_optimism \
          --set ENABLE_PROCESS_BLOCK_RANGE.ethereum=$ENABLE_PROCESS_BLOCK_RANGE_ethereum \
          --set ENABLE_PROCESS_BLOCK_RANGE.polygon=$ENABLE_PROCESS_BLOCK_RANGE_polygon \
          --set ENABLE_PROCESS_BLOCK_RANGE.mantle=$ENABLE_PROCESS_BLOCK_RANGE_mantle \
          --set ENABLE_PROCESS_BLOCK_RANGE.zora=$ENABLE_PROCESS_BLOCK_RANGE_zora \
          --set ENABLE_PROCESS_BLOCK_RANGE.base=$ENABLE_PROCESS_BLOCK_RANGE_base \
          --set ENABLE_PROCESS_BLOCK_RANGE.linea=$ENABLE_PROCESS_BLOCK_RANGE_linea \
          \
          --set dev_rpc_config_values.avalancheTestnet_rpc_url=$DEV_INDEXER_V2_AVALANCHE_TESTNET_RPC_URL \
          --set dev_rpc_config_values.polygonTestnet_rpc_url=$DEV_INDEXER_V2_POLYGON_TESTNET_RPC_URL \
          --set dev_rpc_config_values.polygonTestnetAmoy_rpc_url=$DEV_INDEXER_V2_POLYGON_TESTNET_AMOY_RPC_URL \
          --set dev_rpc_config_values.binanceTestnet_rpc_url=$DEV_INDEXER_V2_BINANCE_SMART_CHAIN_TESTNET_RPC_URL \
          --set dev_rpc_config_values.mantleTestnet_rpc_url=$DEV_INDEXER_V2_MANTLE_TESTNET_RPC_URL \
          --set dev_rpc_config_values.mantleTestnetSepolia_rpc_url=$DEV_INDEXER_V2_MANTLE_TESTNET_SEPOLIA_RPC_URL \
          --set dev_rpc_config_values.ethereumTestnetSepolia_rpc_url=$DEV_INDEXER_V2_ETHEREUM_TESTNET_SEPOLIA_RPC_URL \
          --set dev_rpc_config_values.optimismTestnetSepolia_rpc_url=$DEV_INDEXER_V2_OPTIMISM_TESTNET_SEPOLIA_RPC_URL \
          --set dev_rpc_config_values.arbitrumTestnetSepolia_rpc_url=$DEV_INDEXER_V2_ARBITRUM_TESTNET_SEPOLIA_RPC_URL \
          --set dev_rpc_config_values.zoraTestnetSepolia_rpc_url=$DEV_INDEXER_V2_ZORA_TESTNET_SEPOLIA_RPC_URL \
          --set dev_rpc_config_values.baseTestnetSepolia_rpc_url=$DEV_INDEXER_V2_BASE_TESTNET_SEPOLIA_RPC_URL \
          --set dev_rpc_config_values.lineaTestnetGoerli_rpc_url=$DEV_INDEXER_V2_LINEA_TESTNET_GOERLI_RPC_URL \
          --set dev_rpc_config_values.lineaTestnetSepolia_rpc_url=$DEV_INDEXER_V2_LINEA_TESTNET_SEPOLIA_RPC_URL \
          \
          --set dev_rpc_config_values.private_key=$DEV_INDEXER_V2_PRIVATE_KEY \
          --set dev_rpc_config_values.address=$DEV_INDEXER_V2_DEV_WALLET_ADDRESS \
          --set dev_rpc_config_values.version="beta3" \
          \
          --set datadog_tags.env=${{ env.CLUSTER_NAME }} \
          --set datadog_tags.service=$RELEASE_NAME \
          --set datadog_tags.version=$RELEASE_NAME-${{ env.STG_HOLOGRAPH_INDEXER_HELM_CHART_VERSION }} \
          \
          --set autoscaling.enabled=false \
          --set replicaCountAvalanche=1 \
          --set replicaCountPolygon=1 \
          --set replicaCountBinance=1 \
          --set replicaCountMantle=1 \
          --set replicaCountEthereum=1 \
          --set replicaCountArbitrum=1 \
          --set replicaCountOptimism=1 \
          --set replicaCountBase=1 \
          --set replicaCountLinea=1 \
          --set replicaCountZora=1 \
          \
          --set sqs.SQS_USER_AWS_ACCESS_KEY_ID=$COMMON_AWS_ACCESS_KEY_ID_SQS \
          --set sqs.SQS_USER_AWS_SECRET_ACCESS_KEY=$COMMON_AWS_SECRET_ACCESS_KEY_SQS \
          --set sqs.SQS_ENDPOINT=$DEV_INDEXER_V2_SQS_ENDPOINT \
          --set sqs.SQS_QUEUE_URL=$DEV_INDEXER_V2_SQS_QUEUE_URL \
          --set sqs.AWS_REGION=$COMMON_AWS_REGION
