name: Deploy V2 holoclis to staging[develop-v2]

permissions:
  id-token: write
  contents: read # This is required for actions/checkout@v2

env:
  AWS_REGION: us-west-2
  IAM_ROLE: arn:aws:iam::177635894328:role/Github_role_to_access_ECR
  ECR_REPOSITORY: holo-cli-dev # notice: the same for all cli apps
  #
  IMAGE_TAG: dev-${{ github.sha }}
  #
  CLUSTER_NAME: staging
  #
  AWS_KEY_ID: ${{ secrets.NEWSTAGE_USER_AWS_ACCESS_KEY_ID }}
  AWS_ACCESS_KEY: ${{ secrets.NEWSTAGE_USER_AWS_SECRET_ACCESS_KEY }}

on:
  push:
    branches:
      - 'feat/separate-v1-v2-cli-cicd'
      # Excluded branches
      - '!testnet'
      - '!main'
      - '!mainnet'
      - '!master'

jobs:
  deploy-clis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Initial Setup [composite action]
        uses: ./.github/actions/first-action

      - name: Configure AWS creds to access EKS
        # TIP: the deployment user must be in the masters group in the aws-auth config map in the cluster
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_KEY_ID }} #notice: unique for each env
          aws-secret-access-key: ${{ env.AWS_ACCESS_KEY }} #notice: unique for each env
          aws-region: ${{ env.AWS_REGION }}

#      # NOTICE: --- INDEXER ---
#      - name: Pull the holograph-indexer helm chart version x.x.x from ECR
#        shell: bash
#        env:
#          #
#          CHART_REPO: holo-indexer
#          CHART_VERSION: ${{ env.STG_HOLOGRAPH_INDEXER_HELM_CHART_VERSION }}
#          #
#          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#        run: |
#          helm pull oci://$ECR_REGISTRY/$CHART_REPO --version $CHART_VERSION
#
#      # NOTICE: --- OPERATOR ---
#      - name: Pull the holograph-operator helm chart version x.x.x from ECR
#        shell: bash
#        env:
#          #
#          CHART_REPO: holo-operator
#          CHART_VERSION: ${{ env.STG_HOLOGRAPH_OPERATOR_HELM_CHART_VERSION }}
#          #
#          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#        run: |
#          helm pull oci://$ECR_REGISTRY/$CHART_REPO --version $CHART_VERSION
