name: Deploy V2 holoclis to prod[testnet-v2]

permissions:
  id-token: write
  contents: read # This is required for actions/checkout@v2

env:
  AWS_REGION: us-west-2
  IAM_ROLE: arn:aws:iam::177635894328:role/Github_role_to_access_ECR
  ECR_REPOSITORY: holo-cli # notice: the same for all cli apps
  #
  IMAGE_TAG: testnet-${{ github.sha }}
  #
  CLUSTER_NAME: prod0
  #
  AWS_KEY_ID: ${{ secrets.PROD0_CICD_USER_AWS_ACCESS_KEY_ID }}
  AWS_ACCESS_KEY: ${{ secrets.PROD0_CICD_USER_AWS_SECRET_ACCESS_KEY }}
  #
#  TESTNET_HOLOGRAPH_INDEXER_HOST: 'http://testblondie-holo-api.testnet.svc.cluster.local:443'
#  TESTNET_HOLOGRAPH_OPERATOR_HOST: 'http://testblondie-holo-api.testnet.svc.cluster.local:443'
  #
  # set the RPC endpoints config files
  INDEXER_HOLOGRAPH_CONFIG_FILE_DATA: testnet-config-file
  OPERATOR_HOLOGRAPH_CONFIG_FILE_DATA: testnet-config-file
  #
  HOLOGRAPH_ENVIRONMENT: testnet
  BLOCK_PROCESSING_VERSION: 'V2'
  #
  TESTNET_DOMAIN: 'holograph.xyz' # needed only for the health checks
  #
#  TESTNET_COMMON_NAMESPACE_V2: 'testnet-v2'
  #######################################
  TESTNET_HOLO_INDEXER_HELM_CHART_VERSION: 0.1.85
#  INDEXER_RELEASE_NAME_V2: 'blondie-indexer-testnet-v2' # format -> [release_name]-indexer-[env]
  #
  TESTNET_HOLO_OPERATOR_HELM_CHART_VERSION: 0.1.16
#  OPERATOR_RELEASE_NAME_V2: 'blondie-operator-testnet-v2' # format -> [release_name]-indexer-[env]
  #######################################

# notice: the trigger
#on:
#  push:
#    branches:
#      - 'something'
#      # Excluded branches
#      - '!develop'
#      - '!main'
#      - '!master'
# notice: the trigger
on:
  pull_request:
    branches:
#      - 'testnet'
      - 'deactivated'
    types: [closed]

jobs:
  deploy-clis-testnet:
    if: github.event.pull_request.merged == true # so no workflow runs when some PR is just closed without being merged
    runs-on: ubuntu-latest
    steps:
      #
      - uses: actions/checkout@v4
      #
      - name: Initial Setup [composite action]
        uses: ./.github/actions/testnet/initial-setup
      #
      - name: Deploy Indexer [composite action]
        uses: ./.github/actions/testnet/deploy-indexer
      #
      - name: Pause for 60 seconds
        shell: bash
        run: sleep 60
      #
      - name: Deploy Operator [composite action]
        uses: ./.github/actions/testnet/deploy-operator
      #
      - name: -> V2 -- Info for the new V2 deployments
        uses: tensor-hq/eksctl-helm-action@main
        env:
          INDEXER_RELEASE_NAME: ${{ env.INDEXER_RELEASE_NAME_V2 }}
          OPERATOR_RELEASE_NAME: ${{ env.OPERATOR_RELEASE_NAME_V2 }}
        with:
          eks_cluster: ${{ env.CLUSTER_NAME }}
          command: |-
            echo "------------------------- Last n Helm releases -------------------------"
            echo "--V2 INDEXER--"
            helm history $INDEXER_RELEASE_NAME  -n ${{ env.TESTNET_COMMON_NAMESPACE_V2 }} --max 3
            echo "--V2 OPERATOR--"
            helm history $OPERATOR_RELEASE_NAME -n ${{ env.TESTNET_COMMON_NAMESPACE_V2 }} --max 3

            echo "------------------------ Newly deployed image [same for all apps] ------------------------"
            echo "$IMAGE_TAG"
